### PR TITLE
Correct attribute name: landing_gap_size

### PR DESCRIPTION
**Pull request by seanpk**
ref: `src/ezdxf/render/mleader.py`

### CODE REVIEW

**Comment by mozman** [comment]
Thanks, but it's too late for that. I don't break existing code for that.

**Comment by seanpk** [comment]
I don't understand, I think maybe you misunderstood what the PR was for...?

 The documentation does not match the code. How would updating the documentation, which is what this PR is for, break any existing code?

**Comment by mozman** [comment]
I misunderstood that.

**Comment by mozman** [comment]
Wrong target branch.

**Pull request merged**
