### PR TITLE
Add Linux AArch64 wheel build support

### PR DESCRIPTION
**Pull request by odidev**
Added linux aarch64 wheel build support.
Related to https://github.com/mozman/ezdxf/issues/584, @mozman Could you please review this PR?

### CODE REVIEW

**Comment by mozman** [comment]
Is there no PyPI upload? Or how can I add the PyPI upload? The PyPI upload is the only purpose of this workflow!

**Comment by mozman** [comment]
added upload to PyPI ...

**Comment by mozman** [comment]
Why do you use tag v0.3.4-manylinux2014_aarch64 instead of the latest version v0.4.2-manylinux2014_aarch64?

**Comment by odidev** [comment]
The latest version v0.4.2-manylinux2014_aarch64 was released recently. Before that I was using v0.4.0-manylinux2014_aarch64 which was causing error in auditwheel command due to platform mismatch. So, I used older version. However I just checked with the latest version and it also looks to be working fine.

**Comment by mozman** [comment]
A test run with v0.4.2-manylinux2014_aarch64 and deployment to [TestPyPI](https://test.pypi.org/project/ezdxf/0.17.2b3/#files) was successful.

Can you do a test install with any of these packages?

**Comment by odidev** [comment]
It's working.

**Comment by mozman** [comment]
Thanks for your feedback, but I just changed the workflow to use `pypa/cibuildwheel@v2.3.1` to support more platforms, the first release `v0.17.2b4` is running now (ARM64 build on QEMU takes a looooooong time) and can be tested soon: https://pypi.org/project/ezdxf/0.17.2b4/

**Comment by odidev** [comment]
I installed the wheel and ran tests on both x86 and aarch64. On running the tests on both the platforms,  I'm getting some assertion errors. Please have a look at the logs for the same: 

**Test logs on x86_64:** [ezdxf_test_x86.txt](https://github.com/mozman/ezdxf/files/7734664/ezdxf_test_x86.txt)
**Test logs on aarch64:**[ezdxf_test_arm64.txt](https://github.com/mozman/ezdxf/files/7734665/ezdxf_test_arm64.txt)

**Comment by mozman** [comment]
The x86 tests (205, issue_589) which are failing were added today and can only run with the latest version fro github - the wheels were build yesterday!

Same for the arm64 platform but there are additional floating point impressions error in: 621, 630a, 708b, 906 which I try to solve.

To run the test suite you ALWAYS have to install the latest version from github or you have to use the tests included in the source code distribution for the wheel you use, the tests are not included in the wheels itself. For non-beta releases the "stable" branch is also a way to go.

**Comment by mozman** [comment]
Install current version from github: https://ezdxf.mozman.at/docs/setup.html#installation-from-github

**Pull request merged**
